<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta content=\"Kathrin Hapke, Boris Roßbach\" name=\"author\">\n";
echo "    <link href=\"style.css\" rel=\"stylesheet\">\n";
echo "    <title>Index</title>\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "<header>Dies ist der Header</header>\n";
echo "<nav>\n";
echo "    <a href=\"index.php\">Link zur Startseite</a>\n";
echo "    <a href=\"seite2.php\">Link zur 2. Seite</a>\n";
echo "</nav>\n";
echo "<section>\n";
echo "    <h1>Dies ist die Startseite</h1>\n";
echo "    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et\n";
echo "        dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet\n";
echo "        clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet,\n";
echo "        consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed\n";
echo "        diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea\n";
echo "        takimata sanctus est Lorem ipsum dolor sit amet.</p>\n";
echo "</section>\n";
echo "<footer>Hier steht der Footer</footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
echo "<script src=\"index.js\"></script>\n";
