<?php
echo "<!DOCTYPE html>\n";
echo "<html lang=\"en\">\n";
echo "<head>\n";
echo "    <meta charset=\"UTF-8\">\n";
echo "    <meta content=\"Kathrin Hapke, Boris Roßbach\" name=\"author\">\n";
echo "    <link href=\"style.css\" rel=\"stylesheet\">\n";
echo "    <title>Seite2</title>\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "<header>Dies ist der Header</header>\n";
echo "<nav>\n";
echo "    <a href=\"index.php\">Link zur Startseite</a>\n";
echo "    <a href=\"seite2.php\">Link zur 2. Seite</a>\n";
echo "</nav>\n";
echo "<section>\n";
echo "    <h1>Dies ist Seite 2</h1>\n";
echo "    <!-- entnommen von  https://pixabay.com/de/photos/code-codierung-web-entwicklung-944499/  -->\n";
echo "    <img alt=\"Code Beispiel\" src=\"code-944499_640.jpg\"/>\n";
echo "</section>\n";
echo "<section>\n";
echo "    <h1>Dies ist Seite 2</h1>\n";
echo "    <!-- entnommen von  https://pixabay.com/de/photos/code-codierung-web-entwicklung-944499/  -->\n";
echo "    <img alt=\"Code Beispiel\" src=\"code-944499_640.jpg\"/>\n";
echo "</section>\n";
echo "<section>\n";
echo "    <h1>Dies ist Seite 2</h1>\n";
echo "    <!-- entnommen von  https://pixabay.com/de/photos/code-codierung-web-entwicklung-944499/  -->\n";
echo "    <img alt=\"Code Beispiel\" src=\"code-944499_640.jpg\"/>\n";
echo "</section>\n";
echo "<footer>Hier steht der Footer</footer>\n";
echo "</body>\n";
echo "</html>\n";
echo "\n";
echo "<script src=\"index.js\"></script>\n";
